# Generated by Django 3.0.5 on 2020-05-07 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessory', '0001_initial'),
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleHasAccessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accessory.Accessory')),
                ('console', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='console.Console')),
            ],
        ),
    ]
