# Generated by Django 3.0.5 on 2020-05-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessory', '0003_auto_20200509_1826'),
        ('videogame', '0013_auto_20200509_1826'),
        ('console', '0003_delete_consolehasaccessory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Console',
        ),
    ]
