# Generated by Django 3.0.5 on 2020-05-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_brand_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='website',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
