# Generated by Django 3.0.5 on 2020-05-09 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accessory', '0002_auto_20200507_1442'),
        ('console', '0003_delete_consolehasaccessory'),
        ('videogame', '0012_auto_20200507_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accessory.Accessory')),
                ('console_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='console.Console')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Type')),
                ('videogame_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videogame.VideoGame')),
            ],
        ),
    ]
