# Generated by Django 3.0.5 on 2020-05-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='accessory_id',
            new_name='accessory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='console_id',
            new_name='console',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='videogame_id',
            new_name='videogame',
        ),
    ]
