# Generated by Django 3.0.5 on 2020-05-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogame', '0003_consolehasaccessory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeLimitImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=999)),
            ],
        ),
        migrations.RenameField(
            model_name='videogame',
            old_name='ageLimit',
            new_name='age_limit',
        ),
        migrations.AddField(
            model_name='accessory',
            name='image',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='console',
            name='image',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='videogame',
            name='image',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
