# Generated by Django 3.0.5 on 2020-05-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_brand'),
        ('console', '0001_initial'),
        ('videogame', '0004_auto_20200506_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='brand',
        ),
        migrations.DeleteModel(
            name='AgeLimitImage',
        ),
        migrations.RemoveField(
            model_name='console',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='consolehasaccessory',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='consolehasaccessory',
            name='console',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='release_date',
        ),
        migrations.AlterField(
            model_name='videogame',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.Brand'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='console',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='console.Console'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='image',
            field=models.CharField(max_length=999),
        ),
        migrations.DeleteModel(
            name='Accessory',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Console',
        ),
        migrations.DeleteModel(
            name='ConsoleHasAccessory',
        ),
    ]
