# Generated by Django 3.0.5 on 2020-05-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogame', '0006_videogamehasgenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='release_date',
            field=models.DateField(default=1976),
            preserve_default=False,
        ),
    ]
