# Generated by Django 3.0.5 on 2020-05-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogame', '0009_auto_20200507_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
