# Generated by Django 3.0.5 on 2020-05-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_auto_20200507_1442'),
        ('console', '0003_delete_consolehasaccessory'),
        ('accessory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='console',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='console.Console'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.Brand'),
        ),
    ]
