# Generated by Django 3.0.5 on 2020-05-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessory', '0003_auto_20200509_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='ProductType',
        ),
    ]
