# Generated by Django 3.0.6 on 2020-05-07 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['postal_code']},
        ),
    ]
