# Generated by Django 3.0.5 on 2020-05-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200513_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlyviewed',
            name='date',
            field=models.DateField(default='2020-10-10'),
            preserve_default=False,
        ),
    ]
