# Generated by Django 3.0.5 on 2020-05-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200514_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyviewed',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
