# Generated by Django 3.0.5 on 2020-05-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
