# Generated by Django 3.0.5 on 2020-05-12 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200512_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.ContactInformation'),
            preserve_default=False,
        ),
    ]
