# Generated by Django 3.0.5 on 2020-05-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_delivery_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryMethod',
        ),
    ]
