# Generated by Django 3.0.5 on 2020-05-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_delete_deliverymethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cardholder_first_name',
            new_name='cardholder_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cardholder_last_name',
        ),
    ]
