# Generated by Django 3.0.5 on 2020-05-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.CharField(default='1234567812345678', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='cvv',
            field=models.CharField(default='234', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='exp_date',
            field=models.CharField(default='01/01', max_length=5),
            preserve_default=False,
        ),
    ]
