# Generated by Django 3.0.5 on 2020-05-14 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessory', '0004_auto_20200509_1858'),
        ('order', '0013_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_how_often', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessory.Product')),
            ],
        ),
    ]
