# Generated by Django 3.0.5 on 2020-05-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_bestsellers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsellers',
            name='sold_how_often',
            field=models.IntegerField(null=True),
        ),
    ]
